### ISSUE TITLE
(pcsx2) Shortcut refers to a non-existent executable

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [TheCakeIsNaOH/chocolatey-packages#18]
GitHub Actions builds uses naming with system architecture.
It would also be nice to add support for AVX2 builds (but my laptop can't handle that).

![image](https://user-images.githubusercontent.com/69355938/140261038-2ff186c5-5d82-44c6-bdce-183b27db81b7.png)

**Comment by TheCakeIsNaOH** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou You are talking about the pcsx2-dev package, correct?

**Comment by TheCakeIsNaOH** [comment]
I've added support for AVX2 and fixed the shortcut name in the pcsx2-dev package. You can select the avx2 build with the `UseAVX2` package parameter.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
Thanks. However, why only two files are updating (pcsx2x64.exe and PCSX2_keys.ini.default) when archive contains localization and games database?

**Comment by TheCakeIsNaOH** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou It seems like they just changed the archive format. I've updated the code, see if the next package version is working correctly for you. It seemed to work fine on my machine, but it might not always have worked.

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@TheCakeIsNaOH PCSX2 packages have recently split into [wxWidgets and Qt frontends](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2761) and no longer available on the x86 platform.
