### ISSUE TITLE
(yt-dlp) Install only 64-bit files on 64-bit OS

### ISSUE THREAD

**Issue by opusforlife2** [TheCakeIsNaOH/chocolatey-packages#20]
Is it possible to ensure that the 32-bit binaries and other files aren't installed on a 64-bit OS?

**Comment by TheCakeIsNaOH** [comment]
@opusforlife2 the package is set up so the 32 bit and 64 bit `.exe`s are included in the package, but only the correct one is shimmed.

If that seems to be not happening for you correctly, can you please do `choco uninstall yt-dlp` and then `choco install yt-dlp --verbose --debug` and share the resulting output (sanitized as needed of course).

**Comment by opusforlife2** [comment]
When you say "shimmed", do you mean the shortcut to run the program?

I was looking at the `bin` folder. Are both exes supposed to be there?

**Comment by TheCakeIsNaOH** [comment]
> When you say "shimmed", do you mean the shortcut to run the program?

I mean this: https://docs.chocolatey.org/en-us/features/shim

So basically, yes.

> I was looking at the bin folder. Are both exes supposed to be there?

No they are not, can you do the uninstall and reinstall, as that should help me figure out what is going on.

**Comment by opusforlife2** [comment]
Welp. Like so many tech problems, reinstalling solved the issue. The 32-bit shim is gone. XD

What about the `x86` folder in `tools`? Is that supposed to be there?

**Comment by TheCakeIsNaOH** [comment]
> Welp. Like so many tech problems, reinstalling solved the issue. The 32-bit shim is gone. XD

Well, I'm glad it solved your problem, I'll keep an eye out for any future instances of this sort of thing.

> What about the x86 folder in tools? Is that supposed to be there?

Yes, it is setup like that to eliminate the need for an install script. See info about it here: https://docs.chocolatey.org/en-us/features/shim#i-have-architecture-specific-binaries-to-shim

**Comment by opusforlife2** [comment]
> Yes, it is setup like that to eliminate the need for an install script.

Cool!

Thanks for the help! Closing.
