### ISSUE TITLE
(pcsx2) Packages split into wxWidgets and Qt frontends

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [TheCakeIsNaOH/chocolatey-packages#21]
@TheCakeIsNaOH PCSX2 packages have recently split into [wxWidgets and Qt frontends](https://github.com/PCSX2/pcsx2/releases/tag/v1.7.2764) and no longer available on the x86 platform.

_Originally posted by @aeiouaeiouaeiouaeiouaeiouaeiou in https://github.com/TheCakeIsNaOH/chocolatey-packages/issues/18#issuecomment-1135392570_

**Comment by TheCakeIsNaOH** [comment]
Thanks for letting me know, I'll update the package accordingly as soon as I can.
