### ISSUE TITLE
(winbtrfs) investigate switching to nefcon for inf install

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [TheCakeIsNaOH/chocolatey-packages#23]
## Expected Behavior

It would be good to not have to use AHK to silently install the winbtrfs `.inf`

## Possible Solution

Nefcon should work as an alternative to the current method: 
https://github.com/maharmstone/btrfs/issues/342#issuecomment-761553794
https://github.com/nefarius/nefcon

## Context

Nefcon would have to be packaged on to the Community Repository first.

**Comment by sitiom** [comment]
https://github.com/maharmstone/btrfs/issues/342#issuecomment-1378279323
> As of [`v1.8.2` (release)](https://github.com/maharmstone/btrfs/releases/tag/v1.8.2), installation via `pnputil` works normally now.

**Comment by TheCakeIsNaOH** [comment]
Fixed upstream, pnputil is working.
