### ISSUE TITLE
Add options to install "search filter" and "shell preview" or default to those options

### ISSUE THREAD

**Issue by co-bbrzgruppe** [TheCakeIsNaOH/chocolatey-packages#24]
Corresponding commandline options for installer are

`-with-filter` install search filter
`-with-preview` install shell preview for PDF files

See
https://www.sumatrapdfreader.org/docs/Installer-cmd-line-arguments

**Comment by TheCakeIsNaOH** [comment]
@co-bbrzgruppe those command line options are available for the installer, see the package parameters documentation in the package description: https://community.chocolatey.org/packages/sumatrapdf.install#description
