### ISSUE TITLE
pcsx2-dev: split avx2 version into dedicated `pcsx2-dev-avx2` package

### ISSUE THREAD

**Issue by soredake** [TheCakeIsNaOH/chocolatey-packages#25]
## Expected Behavior
Have `pcsx2-dev-avx2` package.

## Possible Solution
Split avx2 version into dedicated package.

**Comment by TheCakeIsNaOH** [comment]
@soredake is there a reason for this?

The avx2 build can be installed with the `UseAVX2` parameter. Splitting it out to another package would be a breaking change for any current users of the avx2 parameter, as they would have to manually install a different package and transfer their saves.

**Comment by soredake** [comment]
@TheCakeIsNaOH there is no "UseAVX2" parameter, right now avx2 version is installed with ["UseQT" parameter](https://github.com/TheCakeIsNaOH/chocolatey-packages/blob/master/pcsx2-dev/tools/chocolateyinstall.ps1#L28).

**Comment by TheCakeIsNaOH** [comment]
Hmm, looks like you are right, I must have mistakenly removed it. I've added it back in as an option in `1.7.4229-dev`

**Comment by TheCakeIsNaOH** [comment]
Is there a reason you can't enable `useRememberedArgumentsForUpgrades`?
