### ISSUE TITLE
(win-acme) Support installing plugins

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [TheCakeIsNaOH/chocolatey-packages#28]
## Expected Behavior

It would be good if the win-acme package would support having plugins installed.

## Possible Solution
 
The install location may need to be moved to a folder under `Get-ToolsLocation`

## Context

N/A

**Comment by Geogboe** [comment]
@TheCakeIsNaOH I know this issue is closed but is there any chance a parameter could be added that could allow the install location to be customized? For instance `choco install win-acme -y --params "/InstallPath='c:\Program Files\win-acme'"`. Right now I'm using post processing script to move things around after install but it would be nice if this could be done within the package itself. Thanks!

**Comment by TheCakeIsNaOH** [comment]
@Geogboe unfortunately, I'm not sure of a good way to integrate installation location selection into the package, due to the presence of the plugin packages. 

The reason the install location was switched to `$env:ChocolateyToolsLocation` was so there was a persistent location that plugins could be installed to (via the plugin packages), as the previous install location would get cleared during upgrade. Package parameters do not get shared between packages, so there is no direct way to let plugins packages know where they should put the files. 

When you say post processing script, is that a hook script? https://docs.chocolatey.org/en-us/features/hook

**Comment by Geogboe** [comment]
@TheCakeIsNaOH Ah interesting, so if you added a parameter for /InstallDir here then every plugin package would also need to be updated to support that parameter and folks would need to also remember to pass that parameter and that path every time they installed a plugin package. I see now. I guess I haven't been using the plugin packages so didn't consider this. Thanks for clarifying! 

And regarding post processing yep, that's what I've been using. After the package is installed I move it to program files and modify some of the settings.json.
