### ISSUE TITLE
(pcsx2-dev) The community page is broken

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [TheCakeIsNaOH/chocolatey-packages#32]
The [link](https://community.chocolatey.org/packages/pcsx2-dev) to the package is offline since January.

![image](https://github.com/TheCakeIsNaOH/chocolatey-packages/assets/69355938/f8eacec5-b351-45b8-a654-1c8d783a13e9)

**Comment by TheCakeIsNaOH** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou the Chocolatey Community Repository website is not under my control, you would have to contact Chocolatey about this.
