### ISSUE TITLE
(pcsx2.install) Install fails at autohotkey script

### ISSUE THREAD

**Issue by midrare** [TheCakeIsNaOH/chocolatey-packages#33]
## Expected Behavior
Install completes normally.

## Current Behavior
Autohotkey script errors out.

## Steps to Reproduce

1. PCSX2 is not installed, not the `.install` or `.portable` version, either from chocolatey, another package manager, or an unmanaged msi or anything.
2. Start powershell prompt with admin privileges.
3. `choco install pcsx2.install`
4. Observe error popup

![screen01](https://github.com/TheCakeIsNaOH/chocolatey-packages/assets/59168253/779d3869-ddb0-4ace-9782-a54c46574051)

## Your Environment

* Package Version used: `1.6.0`
* Operating System and version: Windows 11 (Microsoft Windows NT 10.0.22631.0)
* Chocolatey version: `2.3.0`
* Install/uninstall gist (optional): https://gist.github.com/midrare/e236f746fc5f13819f5545f0787eb26e

<details>
<summary>Other relevant details</summary>

```batch
C:\Users\Anonymous>assoc .ahk
.ahk=AutoHotkeyScript

C:\Users\Anonymous>ftype AutoHotkeyScript
AutoHotkeyScript="C:\ProgramData\scoop\apps\autohotkey\2.0.17\UX\AutoHotkeyUX.exe" "C:\ProgramData\scoop\apps\autohotkey\2.0.17\UX\launcher.ahk" "%1" %*

C:\Users\Anonymous>where autohotkey
C:\ProgramData\scoop\shims\autohotkey.exe
C:\ProgramData\chocolatey\bin\AutoHotkey.exe
```

</details>

**Comment by TheCakeIsNaOH** [comment]
Thanks for the details, I'll take a look and try to fix it for you.

**Comment by TheCakeIsNaOH** [comment]
This is no longer applicable, as the next stable release is out, and has a working silent install switch.
