### ISSUE TITLE
(win-acme) Support installing 'trimmed' installer using a parameter 

### ISSUE THREAD

**Issue by Geogboe** [TheCakeIsNaOH/chocolatey-packages#38]
It would be neat if the win-acme package could support installing the 'trimmed' version of win-acme using a parameter. 

## Expected Behavior

One way this could work would be to have a parameter provided called `--params /InstallType:Trimmed` or `--params /trimmed` with the default being pluggable to keep things backwards compatible. 

## Possible Solution

- Additional file path variables would need to be added to the chocolatey scripts holding paths to the trimmed version. 
- The au update.ps1 script would need to be updated to download both the pluggable and trimmed versions and update those new file path variables. 
- A parameter check would need to be added to the chocolatey install script that to see if the trimmed version needs to be installed
- The chocolatey uninstall script would probably need to be updated to check and remove both the pluggable and trimmed versions. 

## Context

Currently, win-acme is released as two different packages. A pluggable one and and trimmed one. The pluggable version ships with .NET Core embedded which provides support for external win-acme plugins. The trimmed version utilizes the builtin version of .net on the OS (I think 4.6+) and does not support any external plugins. 

For example: 
- win-acme.v2.2.9.1701.x64.pluggable.zip
- win-acme.v2.2.9.1701.x64.trimmed.zip 

https://www.win-acme.com/reference/plugins/

My use case for this is I don't need plugins and the trimmed version means I won't have to wait for a new version of win-acme to ship in order to have the embedded version of .net patched. .NET gets patched alongside the OS. It's a minor thing but I don't think completely insignificant. 

My other use cases sort of goes back to this comment I made: https://github.com/TheCakeIsNaOH/chocolatey-packages/issues/28#issuecomment-2115767143 about being able to specify the install paths for the package. This is not doable currently using the pluggable version due to plugin dependencies but if a parameter were added to install the trimmed version (which doesn't have plugin dependencies) a path parameter could also be added to specify an installation location **only** when using the trimmed version. 

Appreciate any consideration!

**Comment by TheCakeIsNaOH** [comment]
I'm thinking it might make sense to have an entirely separate package for the trimmed version. This is because if someone installs a plugin, and had previously installed the trimmed version via package parameter, it would be non-obvious why the plugin is not being loaded. 

Any thoughts on your end?
