### ISSUE TITLE
Nextcloud Talk pre-pelease is available

### ISSUE THREAD

**Issue by RTechSn** [TheCakeIsNaOH/chocolatey-packages#40]
Hi. 
They've finally released an installer for Nextcloud Talk Desktop. 
As you are maintaining the package for Nextcloud-Client, could you add this package too?
And thank you for your great work!

https://github.com/nextcloud-releases/talk-desktop/releases/

**Comment by TheCakeIsNaOH** [comment]
Hi, 

They don't have a `.msi` yet: https://github.com/nextcloud/talk-desktop/issues/884

I don't really want to deal with packaging a squirrel `.exe`, as `.msi` installers tend to be much better for a system wide install, and then I may have to add migration code once they add a `.msi`. 

So I'm not interested in adding this package, at least not until they have a MSI.
You could try asking at https://github.com/chocolatey-community/chocolatey-package-requests/issues

**Comment by RTechSn** [comment]
https://github.com/chocolatey-community/chocolatey-package-requests/issues/1566

**Comment by RTechSn** [comment]
There is an MSI installer now.
